name: myenv
channels:
  - conda-forge
  - bioconda
  - r
dependencies:
  - r
  - bioconductor-ggtree
  - python
  - pip
  - pip:
    - requests
    - pandas
    - XlsxWriter
    - openpyxl
    - boto3
    - mysql-connector-python
    - python-dotenv